name = "QCDNUM"
uuid = "4acc4d78-9ad5-435b-99b1-7af0628e6e5b"
authors = ["Francesca Capel <capel.francesca@gmail.com> and contributors"]
version = "0.2.1"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
QCDNUM_jll = "4f99f0f9-6eee-532a-a65d-722344444835"

[weakdeps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[extensions]
QCDNUMHDF5Ext = "HDF5"

[compat]
FunctionWrappers = "1"
HDF5 = "0.16, 0.17"
Libdl = "1"
Parameters = "0.12"
QCDNUM_jll = "~18.0"
julia = "1.10"
