name = "QCDNUM"
uuid = "4acc4d78-9ad5-435b-99b1-7af0628e6e5b"
authors = ["Francesca Capel <capel.francesca@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
QCDNUM_jll = "4f99f0f9-6eee-532a-a65d-722344444835"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Documenter"]
