name: Runtests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64]
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - run: wget https://www.nikhef.nl/\~h24/download/qcdnum170183.tar.gz
      - run: gunzip qcdnum170183.tar.gz
      - run: tar -xvf qcdnum170115.tar
      - run: cd qcdnum-17-01-83
      - run: ./configure
      - run: make
      - run: make install
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
